name: Workflow for ikido action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: self-hosted
    permissions:
      checks: write
      issues: write
      discussions: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ikido-action
        uses: ikido-tech/ikido-github-action
        with :
          username: ${{ secrets.IKIDO_USERNAME }}
          password: ${{ secrets.IKIDO_PASSWORD }}
