name: 'IKIDO action'
description: ''
inputs:
  username:
    description: 'IKIDO username'
    required: true
  password:
    description: 'IKIDO password'
    required: true
  scan-label:
    description: 'Scan label. If settings specified, will use label from settings file'
    required: false
    default: 'result'
  settings:
    description: 'JSON file contains settings for BOM scan'
    required: false
    default: ''
  ikido-url:
    description: 'IKIDO url for perform BOM scan'
    required: false
    default: 'https://app.ikido.tech'
  project-path:
    description: 'Path to PCB project'
    required: false
    default: './'
  s3-bucket:
    description: 'Bucket with ikido-cli binary'
    required: false
    default: 'https://parsed-bom-bucked.s3.eu-north-1.amazonaws.com/ikido'
  github-token:
    description: 'Github instance'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Configure AWS'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1
    - name: 'Download ikido-cli'
      run: |
        aws s3 cp ${{ inputs.s3-bucket }} ./ikido-cli
      shell: bash
    - name: 'Make ikido-cli binary executable'
      run: |
        chmod +x ./ikido-cli
      shell: bash
    - name: 'Configure IKIDO cli'
      run: |
        ./ikido-cli configure --url ${{ inputs.ikido-url }} --username ${{ inputs.username }} --password ${{ inputs.password }}
      shell: bash
    - name: 'Scan PCB project'
      continue-on-error: true
      run: |
        ./ikido-cli scan-cad --project_path ${{ inputs.project-path }} --scan-label ${{ inputs.scan-label }} --export result.zip --settings ${{ inputs.settings }} >> ikido_output.txt
      shell: bash
    - name: Unpack scan result archive
      run: |
        unzip -q result.zip -d result
      shell: bash
    - name: Get ikido platform URL
      run: |
        echo "IKDO_URL=${{ inputs.ikido-url }}" >> $GITHUB_ENV
      shell: bash
    - name: 'Set up python'
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: "Add result comment to the commit"
      run: |
        source venv/bin/activate
        python main.py
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_SENDER_LOGIN: ${{ github.event.sender.login }}
        GITHUB_REPO_HTML_URL: ${{ github.event.repository.html_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_BRANCH: ${{ github.ref }}
      shell: bash
